# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-13 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discografica', '0015_auto_20160504_0610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='imagen',
            field=models.ImageField(default='discografica/static/img/icon-face.png', upload_to='static/img/album'),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='publicacion',
            unique_together=set([('id', 'album', 'cancion')]),
        ),
    ]
