# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-17 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discografica', '0016_auto_20160513_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='imagen',
            field=models.ImageField(default='static/img/no-album.png', upload_to='static/img/album'),
        ),
    ]
