# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-21 15:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discografica', '0017_auto_20160517_1948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artista',
            name='estilo',
        ),
    ]
